#!/usr/bin/env python3
"""Generate a Caesar-cipher decryption program in THCC.

Usage:
    python make_caesar.py WORD [SHIFT] [OUTPUT]

WORD     plaintext, A-Z letters only, up to 8 chars (longer words
         exceed THMM's 256-cell memory once compiled)
SHIFT    Caesar shift used at encryption time, 0-25 (default 3)
OUTPUT   path to write the generated .thcc file (default ./caesar.thcc)

The generated program holds the *encrypted* bytes as constants. Running
it on the THMM simulator decrypts them back to plaintext: read RAM[p0],
RAM[p1], ... as ASCII to recover the original word.

Decryption per character:

    t_i = c_i - shift + 26 - 65   ; in [1, 51]
    q_i = t_i / 26                ; 0 or 1 (the mod-26 quotient)
    p_i = t_i - q_i * 26 + 65     ; back to ASCII A-Z
"""
import string
import sys
from pathlib import Path

# Empirically derived: 8 chars compiles to 236 cells, 9 chars to 268.
# THMM has 256 cells, so 8 is the safe maximum.
MAX_LEN = 8


def encrypt(word: str, shift: int) -> str:
    out = []
    for ch in word.upper():
        if ch not in string.ascii_uppercase:
            raise ValueError(f"only A-Z letters allowed; got {ch!r}")
        out.append(chr(65 + (ord(ch) - 65 + shift) % 26))
    return "".join(out)


def render_thcc(plain: str, shift: int) -> str:
    plain = plain.upper()
    cipher = encrypt(plain, shift)
    lines = [
        "// Caesar-cipher decryption, generated by make_caesar.py.",
        f"// Encrypted: {cipher}",
        f"// Shift:     {shift}",
        f"// Expected:  {plain}",
        "//",
        "// After running, read RAM at p0, p1, ... as ASCII to recover the plaintext.",
        "",
        f"int shift = {shift};",
        "",
        "// Encrypted bytes:",
    ]
    for i, ch in enumerate(cipher):
        lines.append(f"int c{i} = {ord(ch)};    // '{ch}'")
    lines.append("")
    lines.append("// Decrypt each char: p_i = ((c_i - shift + 26 - 65) mod 26) + 65")
    for i in range(len(cipher)):
        lines.append(f"int t{i} = c{i} - shift + 26 - 65;")
        lines.append(f"int q{i} = t{i} / 26;")
        lines.append(f"int p{i} = t{i} - q{i} * 26 + 65;")
    return "\n".join(lines) + "\n"


def main() -> None:
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__, file=sys.stderr)
        sys.exit(0 if args else 2)

    word = args[0]
    shift = int(args[1]) if len(args) >= 2 else 3
    output = Path(args[2]) if len(args) >= 3 else Path("caesar.thcc")

    if not word:
        sys.exit("error: word must not be empty")
    if any(c not in string.ascii_letters for c in word):
        sys.exit("error: word must contain only A-Z letters")
    if len(word) > MAX_LEN:
        sys.exit(f"error: word too long ({len(word)} chars; max {MAX_LEN} fit in 256 cells)")
    if not (0 <= shift <= 25):
        sys.exit("error: shift must be in [0, 25]")

    src = render_thcc(word, shift)
    output.write_text(src)
    cipher = encrypt(word.upper(), shift)
    print(f"wrote {output}")
    print(f"  plaintext:  {word.upper()}")
    print(f"  ciphertext: {cipher}")
    print(f"  shift:      {shift}")


if __name__ == "__main__":
    main()
